name: "DigitalOcean Kubernetes"
description: "Use DigitalOcean Kubernetes in GitHub Actions"
inputs:
  personalAccessToken:
    description: "DigitalOcean Personal Access Token; Used to fetch latest Kubernetes Config."
    required: true
  clusterName:
    description: "The name of the DigitalOcean Kubernetes cluster that you plan to work with."
    required: true
  expirationTime:
    description: "How long the kubeconfig should stay valid for."
    required: false
    default: "600"
  namespace:
    description: "The Kubernetes namespace to operate under."
    required: false
    default: "default"
  version:
    description: "The kubectl version to use."
    required: false
    default: "1.21.9"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "cloud"
  color: "blue"
