name: 'DigitalOcean Kubernetes'
description: 'Use DigitalOcean Kubernetes in GitHub Actions'
inputs:
  personalAccessToken:
    description: 'DigitalOcean Personal Access Token; Used to fetch latest Kubernetes Config.'
    required: true
  clusterName:
    description: 'The name of the DigitalOcean Kubernetes cluster that you plan to work with.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'cloud'
  color: 'blue'
