name: "Run locally"
on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "dist/index.js"
jobs:
  run:
    runs-on: ${{ matrix.os }}
    if: ${{ always() }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      if: github.repository == 'ck99io/dokube'
    - uses: ./
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: ck99io
        expirationTime: 90
        namespace: default
        version: 1.17.4
    - run: kubectl get nodes
    - run: kubectl top nodes
